[build]
  publish = "Frontend"

[[redirects]]
  from = "/*"
  to = "/HTML/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://post-place-backend-ayf9.onrender.com/api/:splat"
  status = 200
  force = true
